config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  scope '(:city)', city: /nizhny/ do
    root 'pages#index'

    get :about, to: 'pages#about'
    get :career, to: 'pages#career'
    get :team, to: 'pages#team'
    get :works, to: 'pages#works'
    get :sale, to: 'pages#sale'

    resources :specialists
    resources :prices

    resources :sales, only: %i[index show]

    resources :orders, only: %i[create show] do
      collection do
        get :pay
      end
    end

    resources :instagram, only: [:index], constraints: lambda { |req| req.format == :json }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :sale

  enum state: { active: 0, paid: 1, canceled: 2 } do
    event :pay do
      transition active: :paid

      after do
        OrderMailer.pay(self).deliver
        OrderMailer.customer_notice(self).deliver
      end
    end

    event :cancel do
      transition active: :canceled
    end
  end

  def create_payment
    self.uuid ||= SecureRandom.uuid

    authorization = {
      username: Rails.application.credentials.payment[:username].to_s,
      password: Rails.application.credentials.payment[:password]
    }

    response = HTTParty.post(
      'https://payment.yandex.net/api/v3/payments',
      basic_auth:
        authorization,
      headers: {
        'Content-Type': 'application/json',
        'Idempotence-Key': uuid.to_s
      },
      body: {
        "amount": {
          "value": city.eql?('moscow') ? sale.price_sale_msk : sale.price_sale_nn,
          "currency": 'RUB'
        },
        "capture": true,
        "confirmation": {
          "type": 'redirect',
          "return_url": "http://127.0.0.1:3000/orders/#{id}"
        },
        "description": "Заказ №#{id}"
      }.to_json
    )

    return nil unless response

    response.parsed_response

    self.payment_id = response['id']
    self.url = response['confirmation']['confirmation_url']
    save
  end
end

app/models/price.rb
class Price < ApplicationRecord
  validates_presence_of :title, :position
end

app/models/sale.rb
class Sale < ApplicationRecord
  enum state: { Абонимент: 0, Сертификат: 1 }
end

app/models/specialist.rb
class Specialist < ApplicationRecord
  has_one_attached :photo

  default_scope { order(weight: :asc) }

  validates :name, :city, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :rememberable, :trackable, :validatable

   def remember_me
     true
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_city

  def set_city
    @cities = YAML.load_file(Rails.root.join('config', 'cities.yml')).with_indifferent_access
    @city_default = :moscow
    @city_key = (params[:city].presence || @city_default).to_sym
    @city = @cities[@city_key]
  end

  def default_url_options
    { city: @city_default == @city_key ? nil : @city_key }
  end
end

app/controllers/instagram_controller.rb
class InstagramController < ApplicationController
  def index
    url = "https://graph.instagram.com/me/media?fields=id,media_type,media_url,permalink&access_token=#{Rails.application.credentials.dig(:instagram, :token)}"

    @media = JSON.parse(Net::HTTP.get(URI(url)))
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_order, only: %i[show]

  def create
    @order = Order.new(order_params)

    sleep 2

    if @order.save
      @order.create_payment
      render json: @order, status: :ok, location: @order.url
    else
      render json: @order.errors, status: :unprocessable_entity
    end
  end

  def show; end

  def pay
    ip = request.remote_ip
    ips = [
      '185.71.76.0/27', '185.71.77.0/27', '77.75.153.0/25', '77.75.154.128/25',
      '2a02:5180:0:1509::/64', '2a02:5180:0:2655::/64', '2a02:5180:0:1533::/64',
      '2a02:5180:0:2669::/64', '127.0.0.1/8', '::1'
    ]

    request = ips.map { |i| IPAddr.new(i).include?(ip) }

    if request.include?(true)
      data = params[:object]
      @order = Order.find_by(payment_id: data[:id])

      if data[:status].eql?('succeeded')
        @order.pay
      else
        @order.cancel
      end
    else
      head :unprocessable_entity
    end
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    permitted = %i[
      sale_id name surname phone
      email city uuid url state
    ]

    params.require(:order).permit(*permitted)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_specialists, only: %i[index team]

  def index
    @prices = Price.all.order(:order)
  end

  def career; end

  def about; end

  def team; end

  def works; end

  private

  def set_specialists
    @specialists = Specialist.with_attached_photo.where(city: @city_key)
  end
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_price, only: [:edit, :update, :destroy]

  def index
    @prices = Price.order(position: :asc, order: :desc, id: :asc).all
  end

  def new
    @price = Price.new
  end

  def create
    @price = Price.new(price_params)

    @price.save
    redirect_to [:prices]
  end

  def edit
  end

  def update
    if @price.update(price_params)
      redirect_to [:prices], notice: 'Prices was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @price.destroy

    redirect_to [:prices]
  end

  private
    def price_params
      params.require(:price).permit(:title, :price_msk, :price_nn, :description, :position, :order)
    end

    def set_price
      @price = Price.find(params[:id])
    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_specialists, only: %i[index show]
  before_action :set_sale, only: %i[show]

  def index
    @sales = Sale.all
  end

  def show
    respond_to do |format|
      format.html { render :index }
      format.json
    end
  end

  private

  def set_sale
    @sale = Sale.find(params[:id])
  end

  def set_specialists
    @specialists = Specialist.with_attached_photo.where(city: @city_key)
  end
end

app/controllers/specialists_controller.rb
class SpecialistsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_specialist, only: [:edit, :update, :destroy]

  def index
    @specialists = Specialist.all
  end

  def new
    @specialist = Specialist.new
  end

  def edit
  end

  def create
    @specialist = Specialist.new(specialist_params)

    if @specialist.save
      redirect_to specialists_path, notice: 'Specialist was successfully created.'
    else
      render :new
    end
  end

  def update
    # render plain: params[:specialist].inspect
    if @specialist.update(specialist_params)

      redirect_to specialists_path, notice: 'Specialist was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @specialist.destroy
    redirect_to specialists_url, notice: 'Specialist was successfully destroyed.'
  end

  private
    def set_specialist
      @specialist = Specialist.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def specialist_params
      params.require(:specialist).permit(:name, :photo, :service, :yid, :weight, :city, :remove_photo)
    end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index

    @media = JSON.parse(open('https://api.instagram.com/v1/users/1388142751/media/recent/?access_token=1388142751.0871ed8.a1fe16d1d5a24294b6304f061fc27512&count=20').read).with_indifferent_access[:data]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def inline_svg(path)
    file = File.open(Rails.root.join('app', 'javascript', 'images') + "#{path}", 'rb')
    raw file.read
  end

  def city
    @city_key == :moscow ? nil : @city_key
  end
end

app/views/layouts/application.html.slim
doctype html
html lang=I18n.locale
  head
    = display_meta_tags site: "RAIN #{@city[:title_ru]}", reverse: true, separator: '—', og: { \
      title: :title,
      image: asset_pack_url('media/images/og.jpg'),
      description: :description \
    }

    = favicon_link_tag '/favicon.ico'
    = csrf_meta_tags

    = tag('meta', { name: 'viewport', content: 'width=device-width, initial-scale=1.0' })

  body
    = react_component 'Geo', {}, { prerender: true } unless cookies[:geo]
    = react_component 'Header', { city: @city_key, sale: params[:controller] === 'sales' && %w(index show).include?(params[:action]), order: params[:controller] === 'orders' && %w(show).include?(params[:action]) }, { prerender: true }
    = yield

    = stylesheet_pack_tag 'app'
    = javascript_pack_tag 'app'
    = stylesheet_link_tag '//fonts.googleapis.com/css?family=Playfair+Display&amp;subset=cyrillic'

    = react_component 'Footer', { city: @city_key }, { prerender: true }

    = javascript_include_tag '//w81206.yclients.com/widgetJS'
    == render '/shared/c'

app/views/orders/show.html.slim
= react_component 'Orders/Show', { order: @order }

app/views/pages/about.html.slim
- set_meta_tags title: 'Пространство', canonical: about_url(city: city), description: 'Приходи. Твоя очередь хорошо себя чувствовать'

= react_component 'Pages/About', { city: @city_key }, { prerender: true }

app/views/pages/career.html.slim
- set_meta_tags title: "Вакансии #{@city[:title_in]}", canonical: career_url(city: city), description: 'Все вакансии пространства RAIN'

= react_component 'Pages/Career', { city: @city_key }, { prerender: true }

app/views/pages/index.html.slim
- set_meta_tags title: "RAIN — ногтевая студия. Заботливый маникюр и педикюр #{@city[:title_in]}.", site: nil, description: "Заботливый маникюр и педикюр #{@city[:title_in]}.", canonical: root_url(city: city), og: { title: "RAIN — ногтевая студия" }

= react_component( \
  'Pages/Index',
  { \
    city: @city_key,
    specialists: SpecialistSerializer.new(@specialists).serializable_hash,
    prices: PriceSerializer.new(@prices).serializable_hash,
    instagram: instagram_index_path(format: :json) \
  }, { \
    prerender: false \
  } \
)

app/views/pages/sale.html.slim
- set_meta_tags title: 'Акции'

= react_component( \
  'Pages/Sale',
  { \
    city: @city_key,
    specialists: @specialists.map { |specialist| specialist.slice(:id, :name, :service).merge({ photo: url_for(specialist.photo.variant(thumbnail: "800x1000", quality: 80, interlace: :plane)) }) }  \
  }, { \
    prerender: true \
  } \
)

app/views/pages/team.html.slim
- set_meta_tags title: 'Команда', canonical: team_url(city: city), description: 'Команда пространства RAIN'

= react_component( \
  'Pages/Team',
  { \
    city: @city_key,
    specialists: SpecialistSerializer.new(@specialists).serializable_hash \
  }, { \
    prerender: true \
  } \
)

 / @specialists.map { |specialist| specialist.slice(:name, :service).merge({ photo: url_for(specialist.photo.variant(thumbnail: "800x1000", quality: 80, interlace: :plane)) }) }

app/views/pages/works.html.slim
- set_meta_tags title: 'Работы'

= react_component 'Pages/Works', { prerender: true }

app/views/prices/_form.html.slim
.form
  = simple_form_for @price do |f|
    = f.error_notification

    .form_inputs
      = f.input :title
      = f.input :price_msk
      = f.input :price_nn
      = f.input :description
      = f.input :position, collection: [['Левый блок', 'left'], ['Правый блок', 'right']]
      = f.input :order, :input_html => { :value => @price.order || '0'}

    .form_actions
      = f.button :submit

app/views/prices/edit.html.slim
main#prices.page.page_index
  h1 Edit prices

  == render 'form'

app/views/prices/index.html.slim
main.page.page_prices
  .prices_control
    h1 Редактирование цен
    = link_to 'Добавить услугу', new_price_path, class: 'control_link'
    - @prices.each do |price|
      .prices_control_item
        .price_title
          = price.title
        .price_variants
          .price_city
            span Цена в Москве:
            => price.price_msk
            i ₽
          .price_city
            span Цена в Нижнем:
            => price.price_nn
            i ₽

        .price_control_item_links
          = link_to 'Редактировать', edit_price_path(price), class: 'control_link'
          =< link_to 'Удалить', price_path(price), method: :delete, class: 'control_link'

app/views/prices/new.html.slim
main#prices.page.page_index
  h1 New prices

  == render 'form'

app/views/sales/index.html.slim
- set_meta_tags title: 'Акции'

= react_component( \
  'Sales/Sale',
  { \
    city: @city_key,
    sales: @sales,
    sale: @sale,
    specialists: @specialists.map { |specialist| specialist.slice(:id, :name, :service).merge({ photo: url_for(specialist.photo.variant(thumbnail: "800x1000", quality: 80, interlace: :plane)) }) }  \
  }, { \
    prerender: true \
  } \
)

app/views/shared/_c.html.erb
<% if Rails.env.production? %>
  <!-- Yandex.Metrika counter -->
  <script type="text/javascript">
    (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
        try {
          w.yaCounter37977640 = new Ya.Metrika({
            id:37977640,
            clickmap:true,
            trackLinks:true,
            accurateTrackBounce:true,
            webvisor:true
          });
        } catch(e) { }
      });

      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = "https://mc.yandex.ru/metrika/watch.js";

      if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
  </script>
  <noscript><div><img src="https://mc.yandex.ru/watch/37977640" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
  <!-- /Yandex.Metrika counter -->
<% end %>

app/views/specialists/_form.html.slim
.form
  = simple_form_for(@specialist) do |f|
    = f.error_notification

    .form_inputs
      = f.input :name
      / - if @specialist.photo.presence
      /   = image_tag @specialist.photo.preview.url
      /   = f.label :remove_photo do
      /     = f.check_box :remove_photo
      /     | Удалить фото
      / - else
      /   = f.file_field :photo
      = f.input :photo, as: :file
      = f.input :service
      = f.input :yid
      = f.input :weight
      = f.input :city, collection: @cities.map{ |i, city| [city[:title_ru], i] }

    .form-actions
      = f.button :submit, "Сохранить"

app/views/specialists/edit.html.slim
main.page.page_specialist
  .page_section.page_section_top.short
    .placeholder

  .page_section
    h1 Редактировать мастера

    == render 'form'

app/views/specialists/index.html.slim
main.page.page_specialists
  .page_section.page_section_top.short
    .placeholder

  .page_section
    .specialists_control
      h1 Редактирование мастеров
      = link_to 'Добавить мастера', new_specialist_path, class: 'control_link'
      - @specialists.each do |specialist|
        .specialists_control_item
          .specialist_title #{specialist.name} (#{specialist.yid})
          
          .specialist_control_item_links
            = link_to 'Редактировать', edit_specialist_path(specialist), class: 'control_link'
            =< link_to 'Удалить', specialist, method: :delete, class: 'control_link'

app/views/specialists/new.html.slim
main.page.page_specialist
  .page_section.page_section_top.short
    .placeholder

  .page_section
    h1 Новый мастер

    == render 'form'